---
- name: Install packages
  community.general.portage: name={{ item }} state=present
  with_items:
    - ['{{ drivers }}']
    - ['{{ lib }}']
    - ['{{ editor }}']
    - ['{{ file_system }}']
    - ['{{ bash }}']
    - ['{{ sys }}']
